# ============================================================
# Base de datos
# ============================================================
spring.datasource.url=${DB_URL:jdbc:h2:mem:guiasdb;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# ============================================================
# JWT
# TODO: Reactivar para Experiencia 2
# ============================================================
# jwt.secret=${JWT_SECRET:dev-secret-key-min-32-chars-long!!}
#jwt.secret=dev-secret-key-min-32-chars-long!!

# ============================================================
# AWS S3
# ============================================================
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${S3_BUCKET_NAME:guias-local}
aws.endpoint.override=${AWS_ENDPOINT_OVERRIDE:}

# ============================================================
# EFS / almacenamiento de PDFs
# ============================================================
efs.mount.path=${EFS_MOUNT_PATH:/mnt/efs}

# ============================================================
# Thread pool para generación asíncrona de PDF
# ============================================================
pdf.async.pool.size=${PDF_ASYNC_POOL_SIZE:4}

# ============================================================
# Actuator
# ============================================================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# ============================================================
# ISSUER Y JWK
# ============================================================

# El emisor del token (Debe coincidir exactamente con el campo "issuer" del JSON)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocrosero.b2clogin.com/49182dae-b700-44dd-8111-dd18494def6f/v2.0/

# La ubicación de las llaves públicas para descifrar la firma del token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://duocrosero.b2clogin.com/duocrosero.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_signupsignin


